<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WrkExpedition', 'doctrine');

/**
 * BaseWrkExpedition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_expedition
 * @property integer $id_fournisseur
 * @property integer $id_transporteur
 * @property integer $id_chauffeur
 * @property string $lettre_voiture
 * @property integer $nb_colis
 * @property integer $nb_palette
 * @property string $immatriculation
 * @property string $rep_signature
 * @property int $id_nature
 * @property string $br_sap
 * @property string $statut
 * @property string $commentaire
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property RefTransporteur $RefTransporteur
 * @property RefChauffeur $RefChauffeur
 * @property RefFournisseur $RefFournisseur
 * @property Doctrine_Collection $WrkExpeditionProduit
 * @property RefNature $RefNature
 * 
 * @method integer             getId_expedItIon()        Returns the current record's "id_expedition" value
 * @method integer             getId_fournIsseur()       Returns the current record's "id_fournisseur" value
 * @method integer             getId_transporteur()      Returns the current record's "id_transporteur" value
 * @method integer             getId_chauffeur()         Returns the current record's "id_chauffeur" value
 * @method string              getLettre_voiture()       Returns the current record's "lettre_voiture" value
 * @method integer             getNb_colis()             Returns the current record's "nb_colis" value
 * @method integer             getNb_palette()           Returns the current record's "nb_palette" value
 * @method string              getImmatrIculatIon()      Returns the current record's "immatriculation" value
 * @method string              getRep_signatuRe()        Returns the current record's "rep_signature" value
 * @method int                 getId_nature()            Returns the current record's "id_nature" value
 * @method string              getBr_sap()               Returns the current record's "br_sap" value
 * @method string              getStatut()               Returns the current record's "statut" value
 * @method string              getCommentaire()          Returns the current record's "commentaire" value
 * @method timestamp           getCreated_at()           Returns the current record's "created_at" value
 * @method timestamp           getUpdated_at()           Returns the current record's "updated_at" value
 * @method RefTransporteur     getRefTransporteur()      Returns the current record's "RefTransporteur" value
 * @method RefChauffeur        getRefChauffeur()         Returns the current record's "RefChauffeur" value
 * @method RefFournisseur      getRefFournisseur()       Returns the current record's "RefFournisseur" value
 * @method Doctrine_Collection getWrkExpeditionProduit() Returns the current record's "WrkExpeditionProduit" collection
 * @method RefNature           getRefNature()            Returns the current record's "RefNature" value
 * @method WrkExpedition       setId_expedItIon()        Sets the current record's "id_expedition" value
 * @method WrkExpedition       setId_fournIsseur()       Sets the current record's "id_fournisseur" value
 * @method WrkExpedition       setId_transporteur()      Sets the current record's "id_transporteur" value
 * @method WrkExpedition       setId_chauffeur()         Sets the current record's "id_chauffeur" value
 * @method WrkExpedition       setLettre_voiture()       Sets the current record's "lettre_voiture" value
 * @method WrkExpedition       setNb_colis()             Sets the current record's "nb_colis" value
 * @method WrkExpedition       setNb_palette()           Sets the current record's "nb_palette" value
 * @method WrkExpedition       setImmatrIculatIon()      Sets the current record's "immatriculation" value
 * @method WrkExpedition       setRep_signatuRe()        Sets the current record's "rep_signature" value
 * @method WrkExpedition       setId_nature()            Sets the current record's "id_nature" value
 * @method WrkExpedition       setBr_sap()               Sets the current record's "br_sap" value
 * @method WrkExpedition       setStatut()               Sets the current record's "statut" value
 * @method WrkExpedition       setCommentaire()          Sets the current record's "commentaire" value
 * @method WrkExpedition       setCreated_at()           Sets the current record's "created_at" value
 * @method WrkExpedition       setUpdated_at()           Sets the current record's "updated_at" value
 * @method WrkExpedition       setRefTransporteur()      Sets the current record's "RefTransporteur" value
 * @method WrkExpedition       setRefChauffeur()         Sets the current record's "RefChauffeur" value
 * @method WrkExpedition       setRefFournisseur()       Sets the current record's "RefFournisseur" value
 * @method WrkExpedition       setWrkExpeditionProduit() Sets the current record's "WrkExpeditionProduit" collection
 * @method WrkExpedition       setRefNature()            Sets the current record's "RefNature" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWrkExpedition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wrk_expedition');
        $this->hasColumn('id_expedition', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_fournisseur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_transporteur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_chauffeur', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('lettre_voiture', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('nb_colis', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nb_palette', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('immatriculation', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('rep_signature', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('id_nature', 'int', 2, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('br_sap', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('statut', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('commentaire', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefTransporteur', array(
             'local' => 'id_transporteur',
             'foreign' => 'id_transporteur'));

        $this->hasOne('RefChauffeur', array(
             'local' => 'id_chauffeur',
             'foreign' => 'id_chauffeur'));

        $this->hasOne('RefFournisseur', array(
             'local' => 'id_fournisseur',
             'foreign' => 'id_fournisseur'));

        $this->hasMany('WrkExpeditionProduit', array(
             'local' => 'id_expedition',
             'foreign' => 'id_expedition'));

        $this->hasOne('RefNature', array(
             'local' => 'id_nature',
             'foreign' => 'id_nature'));
    }
}