<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmSupervisionParametrage', 'doctrine');

/**
 * BaseAdmSupervisionParametrage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $description
 * @property string $valeur
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer                   getId()          Returns the current record's "id" value
 * @method string                    getNom()         Returns the current record's "nom" value
 * @method string                    getDescription() Returns the current record's "description" value
 * @method string                    getValeur()      Returns the current record's "valeur" value
 * @method timestamp                 getCreated_at()  Returns the current record's "created_at" value
 * @method timestamp                 getUpdated_at()  Returns the current record's "updated_at" value
 * @method AdmSupervisionParametrage setId()          Sets the current record's "id" value
 * @method AdmSupervisionParametrage setNom()         Sets the current record's "nom" value
 * @method AdmSupervisionParametrage setDescription() Sets the current record's "description" value
 * @method AdmSupervisionParametrage setValeur()      Sets the current record's "valeur" value
 * @method AdmSupervisionParametrage setCreated_at()  Sets the current record's "created_at" value
 * @method AdmSupervisionParametrage setUpdated_at()  Sets the current record's "updated_at" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmSupervisionParametrage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_supervision_parametrage');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '',
             ));
        $this->hasColumn('nom', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('valeur', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}