<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WrkArrivageProduit', 'doctrine');

/**
 * BaseWrkArrivageProduit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_arrivage_produit
 * @property integer $id_arrivage
 * @property string $ref_produit
 * @property string $br_sap
 * @property int $id_nature
 * @property integer $id_utilisateur
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property WrkArrivage $WrkArrivage
 * @property RefNature $RefNature
 * @property Doctrine_Collection $WrkMouvement
 * 
 * @method integer             getId_arrIvage_produIt() Returns the current record's "id_arrivage_produit" value
 * @method integer             getId_arrIvage()         Returns the current record's "id_arrivage" value
 * @method string              getRef_pRoduit()         Returns the current record's "ref_produit" value
 * @method string              getBr_sap()              Returns the current record's "br_sap" value
 * @method int                 getId_nature()           Returns the current record's "id_nature" value
 * @method integer             getId_utIlIsateur()      Returns the current record's "id_utilisateur" value
 * @method timestamp           getCreated_at()          Returns the current record's "created_at" value
 * @method timestamp           getUpdated_at()          Returns the current record's "updated_at" value
 * @method WrkArrivage         getWrkArrivage()         Returns the current record's "WrkArrivage" value
 * @method RefNature           getRefNature()           Returns the current record's "RefNature" value
 * @method Doctrine_Collection getWrkMouvement()        Returns the current record's "WrkMouvement" collection
 * @method WrkArrivageProduit  setId_arrIvage_produIt() Sets the current record's "id_arrivage_produit" value
 * @method WrkArrivageProduit  setId_arrIvage()         Sets the current record's "id_arrivage" value
 * @method WrkArrivageProduit  setRef_pRoduit()         Sets the current record's "ref_produit" value
 * @method WrkArrivageProduit  setBr_sap()              Sets the current record's "br_sap" value
 * @method WrkArrivageProduit  setId_nature()           Sets the current record's "id_nature" value
 * @method WrkArrivageProduit  setId_utIlIsateur()      Sets the current record's "id_utilisateur" value
 * @method WrkArrivageProduit  setCreated_at()          Sets the current record's "created_at" value
 * @method WrkArrivageProduit  setUpdated_at()          Sets the current record's "updated_at" value
 * @method WrkArrivageProduit  setWrkArrivage()         Sets the current record's "WrkArrivage" value
 * @method WrkArrivageProduit  setRefNature()           Sets the current record's "RefNature" value
 * @method WrkArrivageProduit  setWrkMouvement()        Sets the current record's "WrkMouvement" collection
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWrkArrivageProduit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wrk_arrivage_produit');
        $this->hasColumn('id_arrivage_produit', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_arrivage', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('ref_produit', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('br_sap', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_nature', 'int', 2, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('id_utilisateur', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WrkArrivage', array(
             'local' => 'id_arrivage',
             'foreign' => 'id_arrivage'));

        $this->hasOne('RefNature', array(
             'local' => 'id_nature',
             'foreign' => 'id_nature'));

        $this->hasMany('WrkMouvement', array(
             'local' => 'br_sap',
             'foreign' => 'ref_produit'));
    }
}