<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefInterlocuteur', 'doctrine');

/**
 * BaseRefInterlocuteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $prenom
 * @property string $mail
 * @property int $id_emplacement
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property RefEmplacement $RefEmplacement
 * @property Doctrine_Collection $WrkArrivage
 * @property Doctrine_Collection $WrkUrgence
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getNom()            Returns the current record's "nom" value
 * @method string              getPrenom()         Returns the current record's "prenom" value
 * @method string              getMail()           Returns the current record's "mail" value
 * @method int                 getId_emplacement() Returns the current record's "id_emplacement" value
 * @method timestamp           getCreated_at()     Returns the current record's "created_at" value
 * @method timestamp           getUpdated_at()     Returns the current record's "updated_at" value
 * @method RefEmplacement      getRefEmplacement() Returns the current record's "RefEmplacement" value
 * @method Doctrine_Collection getWrkArrivage()    Returns the current record's "WrkArrivage" collection
 * @method Doctrine_Collection getWrkUrgence()     Returns the current record's "WrkUrgence" collection
 * @method RefInterlocuteur    setId()             Sets the current record's "id" value
 * @method RefInterlocuteur    setNom()            Sets the current record's "nom" value
 * @method RefInterlocuteur    setPrenom()         Sets the current record's "prenom" value
 * @method RefInterlocuteur    setMail()           Sets the current record's "mail" value
 * @method RefInterlocuteur    setId_emplacement() Sets the current record's "id_emplacement" value
 * @method RefInterlocuteur    setCreated_at()     Sets the current record's "created_at" value
 * @method RefInterlocuteur    setUpdated_at()     Sets the current record's "updated_at" value
 * @method RefInterlocuteur    setRefEmplacement() Sets the current record's "RefEmplacement" value
 * @method RefInterlocuteur    setWrkArrivage()    Sets the current record's "WrkArrivage" collection
 * @method RefInterlocuteur    setWrkUrgence()     Sets the current record's "WrkUrgence" collection
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefInterlocuteur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_interlocuteur');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nom', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('prenom', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('mail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('id_emplacement', 'int', 11, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefEmplacement', array(
             'local' => 'id_emplacement',
             'foreign' => 'code_emplacement'));

        $this->hasMany('WrkArrivage', array(
             'local' => 'id',
             'foreign' => 'id_interlocuteur'));

        $this->hasMany('WrkUrgence', array(
             'local' => 'id',
             'foreign' => 'id_interlocuteur'));
    }
}