<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefFerie', 'doctrine');

/**
 * BaseRefFerie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ferie
 * @property date $date
 * @property string $libelle
 * 
 * @method integer  getId_ferIe() Returns the current record's "id_ferie" value
 * @method date     getDate()     Returns the current record's "date" value
 * @method string   getLibeLLe()  Returns the current record's "libelle" value
 * @method RefFerie setId_ferIe() Sets the current record's "id_ferie" value
 * @method RefFerie setDate()     Sets the current record's "date" value
 * @method RefFerie setLibeLLe()  Sets the current record's "libelle" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefFerie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_ferie');
        $this->hasColumn('id_ferie', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('libelle', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}