<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefWidget', 'doctrine');

/**
 * BaseRefWidget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_widget
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $WrkGroupWidget
 * 
 * @method integer             getId_wIdget()      Returns the current record's "id_widget" value
 * @method string              getName()           Returns the current record's "name" value
 * @method timestamp           getCreated_at()     Returns the current record's "created_at" value
 * @method timestamp           getUpdated_at()     Returns the current record's "updated_at" value
 * @method Doctrine_Collection getWrkGroupWidget() Returns the current record's "WrkGroupWidget" collection
 * @method RefWidget           setId_wIdget()      Sets the current record's "id_widget" value
 * @method RefWidget           setName()           Sets the current record's "name" value
 * @method RefWidget           setCreated_at()     Sets the current record's "created_at" value
 * @method RefWidget           setUpdated_at()     Sets the current record's "updated_at" value
 * @method RefWidget           setWrkGroupWidget() Sets the current record's "WrkGroupWidget" collection
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefWidget extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_widget');
        $this->hasColumn('id_widget', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'primary' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WrkGroupWidget', array(
             'local' => 'id_widget',
             'foreign' => 'id_widget'));
    }
}