<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefHoraire', 'doctrine');

/**
 * BaseRefHoraire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_horaire
 * @property integer $jour
 * @property boolean $fermer
 * @property time $heure_debut
 * @property time $heure_fin
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer    getId_horaIre()  Returns the current record's "id_horaire" value
 * @method integer    getJour()        Returns the current record's "jour" value
 * @method boolean    getFermer()      Returns the current record's "fermer" value
 * @method time       getHeure_debut() Returns the current record's "heure_debut" value
 * @method time       getHeure_fin()   Returns the current record's "heure_fin" value
 * @method timestamp  getCreated_at()  Returns the current record's "created_at" value
 * @method timestamp  getUpdated_at()  Returns the current record's "updated_at" value
 * @method RefHoraire setId_horaIre()  Sets the current record's "id_horaire" value
 * @method RefHoraire setJour()        Sets the current record's "jour" value
 * @method RefHoraire setFermer()      Sets the current record's "fermer" value
 * @method RefHoraire setHeure_debut() Sets the current record's "heure_debut" value
 * @method RefHoraire setHeure_fin()   Sets the current record's "heure_fin" value
 * @method RefHoraire setCreated_at()  Sets the current record's "created_at" value
 * @method RefHoraire setUpdated_at()  Sets the current record's "updated_at" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefHoraire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_horaire');
        $this->hasColumn('id_horaire', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('jour', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fermer', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('heure_debut', 'time', null, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('heure_fin', 'time', null, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}