<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WrkExpeditionProduit', 'doctrine');

/**
 * BaseWrkExpeditionProduit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_expedition_produit
 * @property integer $id_expedition
 * @property string $ref_produit
 * @property string $br_sap
 * @property int $id_nature
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property WrkExpedition $WrkExpedition
 * @property RefNature $RefNature
 * 
 * @method integer              getId_expedItIon_produIt() Returns the current record's "id_expedition_produit" value
 * @method integer              getId_expedItIon()         Returns the current record's "id_expedition" value
 * @method string               getRef_pRoduit()           Returns the current record's "ref_produit" value
 * @method string               getBr_sap()                Returns the current record's "br_sap" value
 * @method int                  getId_nature()             Returns the current record's "id_nature" value
 * @method timestamp            getCreated_at()            Returns the current record's "created_at" value
 * @method timestamp            getUpdated_at()            Returns the current record's "updated_at" value
 * @method WrkExpedition        getWrkExpedition()         Returns the current record's "WrkExpedition" value
 * @method RefNature            getRefNature()             Returns the current record's "RefNature" value
 * @method WrkExpeditionProduit setId_expedItIon_produIt() Sets the current record's "id_expedition_produit" value
 * @method WrkExpeditionProduit setId_expedItIon()         Sets the current record's "id_expedition" value
 * @method WrkExpeditionProduit setRef_pRoduit()           Sets the current record's "ref_produit" value
 * @method WrkExpeditionProduit setBr_sap()                Sets the current record's "br_sap" value
 * @method WrkExpeditionProduit setId_nature()             Sets the current record's "id_nature" value
 * @method WrkExpeditionProduit setCreated_at()            Sets the current record's "created_at" value
 * @method WrkExpeditionProduit setUpdated_at()            Sets the current record's "updated_at" value
 * @method WrkExpeditionProduit setWrkExpedition()         Sets the current record's "WrkExpedition" value
 * @method WrkExpeditionProduit setRefNature()             Sets the current record's "RefNature" value
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWrkExpeditionProduit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wrk_expedition_produit');
        $this->hasColumn('id_expedition_produit', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_expedition', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('ref_produit', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('br_sap', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_nature', 'int', 2, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WrkExpedition', array(
             'local' => 'id_expedition',
             'foreign' => 'id_expedition'));

        $this->hasOne('RefNature', array(
             'local' => 'id_nature',
             'foreign' => 'id_nature'));
    }
}