<?php

/**
 * AdmSpoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmSpoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmSpoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmSpool');
    }
}