<?php

/**
 * AdmSupervisionParametrageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmSupervisionParametrageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmSupervisionParametrageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmSupervisionParametrage');
    }
}