<?php

/**
 * RefChauffeurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefChauffeurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefChauffeurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefChauffeur');
    }
}