<?php

/**
 * RefDestinataireAcheminementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefDestinataireAcheminementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefDestinataireAcheminementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefDestinataireAcheminement');
    }
}