<?php

/**
 * RefInterlocuteurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefInterlocuteurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefInterlocuteurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefInterlocuteur');
    }
}