<?php

/**
 * RefNature
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefNature extends BaseRefNature {

    const NATURE_STANDARD = 1;
    const NATURE_URGENT = 2;
    const NATURE_CONGELEE = 3;

}
