<?php

/**
 * RefNatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefNatureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefNatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefNature');
    }
}