<?php

/**
 * RefTransporteur
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    dev.mobilestock.fr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class RefTransporteur extends BaseRefTransporteur
{
	/*l'objet RefTransporteur renvoi par defaut la designation*/
	public function __toString()
	{
		return sprintf('%s', $this->getDesigTransp());
	}

	/* renvoi le nombre de palette livré avec un transporteur , le type permet d'isoler un type de palette particulier */
	public function getNbPaletteConsignee($type=null)
	{
		$nbPalette = 0;
		//liste des nb_palette_empile dans ref_colis dont les expedition sont geré par le transporteur
		$q = Doctrine_Query::create()->select('sum(r.nb_palette_empile) as nb')->
			from('RefColis r')->innerJoin('r.RefExpeditionCli rec ')->innerJoin('rec.RefExpedition re')
			->where('re.id_livreur = ?', $this->getCodeTransp());
		if($type)$q->andWhere('r.type_palette = ?', $type);
		$nbPalette+=$q->fetchOne()->getNb();
		//liste des nb_palette dans les historisation

		$q = Doctrine_Query::create()->from('HisColis r')->select('sum(r.nb_palette_empile) as nb')->
			where('r.id_expedition_cli IN (SELECT h.id_expedition_cli FROM HisExpeditionCli h
							WHERE h.num_expedition IN (SELECT he.num_expedition FROM HisExpedition he WHERE he.id_livreur = ?)) ', $this->getCodeTransp());
		if($type)$q->andWhere('r.type_palette = ?', $type);
		$nbPalette+=$q->fetchOne()->getNb();
		return $nbPalette;
	}

	public function getNbPaletteRetournee($type=null)
	{
		return 0;
	}
}