<?php

/**
 * RefWidgetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefWidgetTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object RefWidgetTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('RefWidget');
    }

    public function getWidgetWithGroupId($idGroups = array()) {
        return $this->createQuery()->select('w.id_widget,w.name')
                        ->from('RefWidget w')
                        ->innerJoin('w.WrkGroupWidget gw')
                        ->whereIn('gw.group_id', $idGroups)
                        ->orderBy('gw.ordre ASC')
                        ->execute()
                        ->toKeyValueArray('id_widget', 'name');
    }

    public function getAllWidgetSortByOrdre($idGroup) {
        return $this->createQuery()->select('w.id_widget,w.name')
                        ->from('RefWidget w')
                        ->leftJoin('w.WrkGroupWidget gw ON w.id_widget = gw.id_widget AND gw.group_id = ?', $idGroup)
                        ->orderBy('gw.ordre ASC')
                        ->execute();
    }

}
