<?php

/**
 * WrkAcheminement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MobileStockV3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WrkAcheminement extends BaseWrkAcheminement
{
    /* Retourne tous les colis de l'achemiement sous forme d une collection */
    public function getListeColis(){
        
        $q = Doctrine_Query::create()->from('WrkAcheminement w')
			->where('w.num_acheminement = ?', $this->getNumAcheminement())
            ->orderBy('w.suffix_colis', 'ASC');

		return $q->execute();        
    }
    
    
}