<?php

/**
 * WrkArrivageProduitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WrkArrivageProduitTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object WrkArrivageProduitTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('WrkArrivageProduit');
    }

    public function getReceptions($heureDebut = '', $heureFin = '', $produit = '', $brSap = '') {
        $req = $this->createQuery()
                ->select('a.*')
                ->from('WrkArrivageProduit a')
                ->andWhere('a.br_sap != ?', "")
                ->orderBy('a.created_at desc');

        if ($heureDebut != '') {
            $req->andWhere('a.created_at >=?', $heureDebut);
        }
        if ($heureFin != '') {
            $req->andWhere('a.created_at <=?', $heureFin);
        }
        if ($produit != '') {
            $req->andWhere('a.ref_produit = ?', $produit);
        }
        if ($brSap != '') {
            $req->andWhere('a.br_sap LIKE ?', '%'.$brSap.'%');
        }

        return $req->execute();
    }

    public function getProduits($idArrivage) {
        return $this->createQuery()
                        ->select('a.ref_produit')
                        ->from('WrkArrivageProduit a')
                        ->where('a.id_arrivage = ?', $idArrivage)
                        ->groupBy('a.ref_produit')
                        ->execute();
    }

}
