<?php

/**
 * WrkExpeditionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WrkExpeditionTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object WrkExpeditionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('WrkExpedition');
    }

    public function getExpeditions($heureDebut = '', $heureFin = '', $fournisseur = '', $transporteur = '', $statut = '', $produit = '') {
        $req = $this->createQuery()
                ->select('w.*,f.*,t.*,c.*,n.*,ap.*')
                ->from('WrkExpedition w')
                ->leftJoin('w.RefFournisseur f')
                ->leftJoin('w.RefTransporteur t')
                ->leftJoin('w.RefChauffeur c')
                ->leftJoin('w.RefNature n')
                ->leftJoin('w.WrkExpeditionProduit ap')
                ->orderBy('w.created_at desc');

        if ($heureDebut != '') {
            $req->andWhere('w.created_at >=?', $heureDebut);
        }
        if ($heureFin != '') {
            $req->andWhere('w.created_at <=?', $heureFin);
        }
        if ($fournisseur != '') {
            $req->andWhere('w.id_fournisseur= ?', $fournisseur);
        }
        if ($transporteur != '') {
            $req->andWhere('w.id_transporteur = ?', $transporteur);
        }
        if ($statut != '') {
            $req->andWhere('w.statut = ?', $statut);
        }
        if ($produit != '') {
            $subReq = $this->createQuery()->select('ap2.id_expedition')->from('wrk_expedition_produit ap2')->where('ap2.ref_produit = ?', $produit);
            $req->andWhere('w.id_expedition IN(' . $subReq->getDql() . ')', $produit);
        }

        return $req->execute();
    }

    /**
     * Retourne la date de la derniere expedition ou la date du jour si il n'y a pas d'expedition
     * @return type
     */
    public function getDernierExpeditionDate() {
        $dateArray = $this->createQuery()
                ->select('MAX(DATE(a.created_at))')
                ->from('WrkExpedition a')
                ->fetchArray();

        if (count($dateArray) > 0) {
            return date('d/m/Y', strtotime($dateArray[0]['MAX']));
        }
        return date('d/m/Y');
    }

}
