<?php

/**
 * WrkExpeditionProduitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WrkExpeditionProduitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WrkExpeditionProduitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WrkExpeditionProduit');
    }
}