<?php

/**
 * WrkGroupWidgetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WrkGroupWidgetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WrkGroupWidgetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WrkGroupWidget');
    }
}