<?php

/**
 * sfGuardGroup
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    licence
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sfGuardGroup extends PluginsfGuardGroup
{
	/* fonction qui retourne seulement les groupes n'ayant pas les droits utilisateurs et groupes */
	/*
	public function getGroupsWithBasicsRights()
	{
		$nom_permissions = array();
		$droit_avances = array ('gestion des utilisateurs niveau 1','gestion des utilisateurs niveau 2',
                                 'gestion des groupes');
		//pour chacune des permissions du groupe
		foreach ($this->getPermissions() as $permission):
			$nom_permissions[]= $permission->getName();
		endforeach;
		//si le groupe en cours n'a pas des permission avance on retourne son nom
		$diff = array_diff($droit_avances,$nom_permissions) ;
		if (count($diff) == sizeof($droit_avances)) {return $this->getName();}
		else return null;
	}*/

	/* verifie qu'un groupe à la permission passée en parametre
	   retourne vrai ou faux   */
	public function aLeDroit($droit)
	{
		$lesPermissions = array();
		foreach ($this->getPermissions() as $permission):
			$lesPermissions[] = $permission->getName();
		endforeach;
		return in_array($droit,$lesPermissions );
	}

	/* ajoute une permission ecran au groupe */
	public function accordeDroit(SfGuardPermission $permission)
	{
		$permissionGroupe = new sfGuardGroupPermission();
		$permissionGroupe->setSfGuardGroup($this);
		$permissionGroupe->setSfGuardPermission($permission);
		return $permissionGroupe->save();
	}

	/* supprime une permission ecran au groupe */
	public function supprimeDroit(SfGuardPermission $permission)
	{
		$permissionGroupe = doctrine::getTable('SfGuardGroupPermission')->find(array($this->getId(), $permission->getId()));
		//si le groupe a bien la permission
		if($permissionGroupe){
			$permissionGroupe->delete();
			return true;
		}
		else return false;
	}

	/* supprime une permission ecran au groupe, le parametre est le nom du droit */
	public function supprimeDroitParNom($nomPermission)
	{
		$q = Doctrine_Query::create()->from('SfGuardPermission')->where('name = ?', $nomPermission);
		if($permission = $q->fetchOne()) {
			$this->supprimeDroit($permission);
			return true;
		}
		else return false;

	}

	/* ajoute une permission ecran au groupe, le parametre est le nom du droit */
	public function ajouteDroitParNom($nomPermission)
	{
		$q = Doctrine_Query::create()->from('SfGuardPermission')->where('name = ?', $nomPermission);
		if($permission = $q->fetchOne()) {
			$this->accordeDroit($permission);
			return true;
		}
		else return false;

	}

}