# Ce fichier gere les droits accordés aux groupes concernant la gestion des utilisateurs

#menu reservé au SU et chef de quai
all:
  is_secure: on
  credentials: [[ gestion des utilisateurs, gestion des utilisateurs niveau 1, gestion des utilisateurs niveau 2]]
editPassword:
    is_secure: false 
updatePassword:
    is_secure: false 